"""
Agent control loop: observe (user message) -> reason (LLM call with
tools) -> act (execute tool) -> feed result back -> continue, until
the model produces a final answer with no more tool calls, or a
safety iteration limit is hit.

Conversation history is kept in memory per session_id and is
intentionally NOT persisted -- a `/new` chat (or a process restart)
starting a fresh conversation is expected behaviour. What IS
persisted (in the database, via app/services/*) is all durable
business state: stock, bills, khata, and owner preferences. That is
what "memory survives a restart" means for this project -- the store
remembers how it runs; the chat window does not need to.
"""

import json

from groq import Groq

from app.config import GROQ_API_KEY, GROQ_MODEL, AGENT_MAX_ITERATIONS
from app.agent.tools import TOOLS, execute_tool


# ============================================================
# CLIENT
# ============================================================

if not GROQ_API_KEY:
    raise ValueError(
        "GROQ_API_KEY not found. Please add it to your .env file "
        "(see .env.example)."
    )

client = Groq(api_key=GROQ_API_KEY)


# ============================================================
# SYSTEM PROMPT
# ============================================================

SYSTEM_PROMPT = """
You are the AI agent for an Indian supermarket / kirana store.

You operate the supermarket entirely through tools connected to a
real database. You have no state of your own besides this
conversation -- every fact about stock, bills, customers, khata, or
preferences must come from a tool call.

IMPORTANT RULES:

1. Never invent products, prices, stock quantities, GST values,
   bill totals, customer information, sales data, or preferences.

2. Always use tools to obtain real database information. If you are
   not sure a fact is current, call a tool rather than assume.

3. If a product name is ambiguous (a tool returns multiple matches),
   ask the owner to clarify. Do not guess which one they meant.

4. For billing, always create a draft bill first, then add items to
   it one at a time using add_item_to_bill.

5. Before editing or removing a bill item, use conversation context
   and, if needed, get_bill_details to confirm which bill and
   product the owner means.

6. Do not finalize a bill unless the owner clearly wants to complete
   the sale. finalize_bill requires a payment mode (CASH, UPI, or
   CARD) -- ask for it if it hasn't been given.

7. Never claim an operation succeeded unless the tool result has
   success=True. If a tool reports insufficient stock, an already
   finalized bill, or any other failure, tell the owner plainly what
   went wrong -- do not soften it into a success.

8. Stock is only deducted when a bill is finalized, never when items
   are added to a draft.

9. For khata (credit) operations, use find_or_create_customer first
   whenever you don't already know the customer_id from this
   conversation.

10. Generate a GST invoice only for a bill that has already been
    finalized.

11. When the owner asks for a sales report, sales analysis, daily
    presentation, PowerPoint, or PPT, use generate_sales_analysis.
    Never invent sales figures yourself -- the tool retrieves real
    data and real charts.

12. If the owner asks for "today's" report, call the tool without a
    date. If they give a specific date, pass it as YYYY-MM-DD.

13. After generating a file (PDF invoice or PPTX report), mention
    the file name returned by the tool. The file itself will be
    delivered to the owner separately as an attachment -- you do not
    need to describe its contents in exhaustive detail.

14. You may call several tools in a row within the same turn when a
    request needs it (e.g. create a bill, then add multiple items).

15. Keep responses concise and in plain language suitable for a busy
    shop owner texting on their phone.

16. If a tool call fails, explain the failure in plain terms. Do not
    retry the exact same call with the exact same arguments expecting
    a different result -- ask the owner for clarification instead.
"""


# ============================================================
# CONVERSATION SESSIONS (in-memory; see module docstring)
# ============================================================

sessions = {}

# Files generated by tool calls during the most recent run_agent()
# call for a given session, so the caller (Telegram bot / API) can
# deliver them as attachments without changing run_agent's return
# type (kept as a plain string for backward compatibility).
_last_generated_files = {}


def get_session(session_id):
    if session_id not in sessions:
        sessions[session_id] = [{"role": "system", "content": SYSTEM_PROMPT}]
    return sessions[session_id]


def clear_session(session_id):
    sessions[session_id] = [{"role": "system", "content": SYSTEM_PROMPT}]
    _last_generated_files.pop(session_id, None)

    return {
        "success": True,
        "message": f"Session '{session_id}' cleared successfully."
    }


def get_last_generated_files(session_id):
    """
    Files (PDF/PPTX paths) produced by tool calls during the most
    recent run_agent() call for this session. Cleared each time
    run_agent() is called again.
    """
    return _last_generated_files.get(session_id, [])


# ============================================================
# AGENT CONTROL LOOP
# ============================================================

def run_agent(user_message, session_id="default"):
    messages = get_session(session_id)
    generated_files = []

    messages.append({"role": "user", "content": user_message})

    iteration = 0

    while iteration < AGENT_MAX_ITERATIONS:
        iteration += 1

        try:
            response = client.chat.completions.create(
                model=GROQ_MODEL,
                messages=messages,
                tools=TOOLS,
                tool_choice="auto"
            )

        except Exception as e:
            _last_generated_files[session_id] = generated_files
            return f"Unable to communicate with the AI service. Error: {str(e)}"

        message = response.choices[0].message
        messages.append(message)

        # ====================================================
        # NO TOOL CALLS -> final answer
        # ====================================================

        if not message.tool_calls:
            _last_generated_files[session_id] = generated_files
            return message.content or "I could not generate a response."

        # ====================================================
        # EXECUTE TOOL CALLS
        # ====================================================

        for tool_call in message.tool_calls:
            tool_name = tool_call.function.name

            try:
                arguments = json.loads(tool_call.function.arguments)
            except json.JSONDecodeError:
                result = {
                    "success": False,
                    "message": f"Invalid arguments received for tool '{tool_name}'."
                }
            else:
                try:
                    result = execute_tool(tool_name, arguments)
                except Exception as e:
                    result = {
                        "success": False,
                        "message": f"Error executing tool '{tool_name}': {str(e)}"
                    }

            if isinstance(result, dict) and result.get("success") and result.get("file"):
                generated_files.append(result["file"])

            messages.append({
                "role": "tool",
                "tool_call_id": tool_call.id,
                "content": json.dumps(result, default=str)
            })

    _last_generated_files[session_id] = generated_files
    return "The request required too many processing steps. Please try again with a simpler request."


# ============================================================
# OPTIONAL DIRECT TEST
# ============================================================

if __name__ == "__main__":
    print("=" * 60)
    print("SUPERMARKET OPS AGENT")
    print("Type 'exit' to stop.")
    print("=" * 60)

    while True:
        user_input = input("\nYou: ")

        if user_input.lower() in ["exit", "quit", "stop"]:
            print("Agent stopped.")
            break

        print("\nAgent:")
        print(run_agent(user_input))
